## Lab-13 ( LAB WORK)
## DATE : 12-09-25
## NAME: REENA SRI G (22MID0009)

### Dealing with Numpy functions and arrays 

## 1 . Creating Numpy Arrays

In [1]:
#1 . Creating Numpy Arrays
import numpy as np

# Creating array from Python list
arr1 = np.array([1, 2, 3, 4, 5])
print("Array:", arr1)


Array: [1 2 3 4 5]


## 2. Array Dimension, Size, Shape

In [3]:
# 2. Array Dimension, Size, Shape
arr2 = np.array([[1, 2, 3], [4, 5, 6]])  # 2D array

print("Array:\n", arr2)
print("Dimension:", arr2.ndim)   # 2 (2D array)
print("Size:", arr2.size)        # Total number of elements
print("Shape:", arr2.shape)      # (2, 3) => 2 rows, 3 columns


Array:
 [[1 2 3]
 [4 5 6]]
Dimension: 2
Size: 6
Shape: (2, 3)


In [4]:
# comparing 1 and 2 dimensions , how it is stored
print("Dimension:", arr1.ndim) # 1D array

Dimension: 1


In [5]:
# comparing 1 and 2 shape , how it is stored
print("Shape:", arr1.shape) # 1 d array

Shape: (5,)


## Explanation:
- Why is it not ? 1,5 --> it has only 1 row and 5 columns
- ans : it memory space , 1d arrays are stoed at subsequent memory locations and therefore , they are stored as 1 single roes , just like a stack
## 3. eye() function (Identity Matrix)

In [6]:
#3. eye() function (Identity Matrix)
eye_arr = np.eye(4)   # 4x4 identity matrix
print("Identity Matrix:\n", eye_arr)


Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
print(np.eye(3,5)) #5 indicates overall columns

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [9]:
np.eye(3,5,k=1) # k value indicates shifted values over rows and colums, here it is positive , thefore column shift

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [10]:
np.eye(3,5,k=-2) # k value indicates shifted values over rows and colums, here it is negative , therefore row shift

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

## 4. linspace() (Evenly spaced numbers between a range)

In [11]:
# 4. linspace() (Evenly spaced numbers between a range)
lin_arr = np.linspace(0, 10, 5)  # 5 numbers between 0 and 10
print("Linspace:", lin_arr)


Linspace: [ 0.   2.5  5.   7.5 10. ]


## Explanation:
- ### numpy.linspace will create arrays with a specified number of elements, and spaced equally between the specified beginning and end values.

## 5. arange() (Similar to Python’s range but for arrays)

In [12]:
#5. arange() (Similar to Python’s range but for arrays)
arange_arr = np.arange(0, 10, 2)  # From 0 to 10 with step 2
print("Arange:", arange_arr)
# we use step value here

Arange: [0 2 4 6 8]


## Explanation:
- #best practice for numpy.arange is to use integer start, end, and step values.
- arange is specifically used for numpy arrays

## 6. zeros() (Array of zeros)

In [13]:
# 6. zeros() (Array of zeros)
zeros_arr = np.zeros((3, 4))   # 3x4 matrix filled with zeros
print("Zeros Array:\n", zeros_arr)


Zeros Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## 7. random() functions

In [15]:
#7. random() functions
# Random values between 0 and 1
rand_arr = np.random.rand(2, 3)  # random values in 2 rows , 3 column matrix format 
print("Random Array:\n", rand_arr)

# Random integers between 1 and 10
rand_int_arr = np.random.randint(1, 10, (3, 3))  # can specify the range of values along with matrix dimension
print("Random Integers:\n", rand_int_arr)

# Normal distribution (mean=0, std=1)
rand_normal = np.random.randn(3, 3)  
print("Random Normal Distribution:\n", rand_normal)


Random Array:
 [[0.12047731 0.16954618 0.15376204]
 [0.10825606 0.08893019 0.37257353]]
Random Integers:
 [[7 9 6]
 [7 6 9]
 [2 9 6]]
Random Normal Distribution:
 [[ 0.0874856   0.4621275  -0.22146105]
 [-0.3369807   0.68787804 -0.93549525]
 [ 0.99334366 -0.08027811 -0.14412556]]


## 8. Program discussed in class 

In [17]:
# 8. Program discussed in class 
def pythonsum(n):
    a = [0] * n
    b = [0] * n
    c = []
    for i in range(n):
        a[i] = i ** 2
        b[i] = i ** 3
        c.append(a[i] + b[i])
    return c
   
pythonsum(4)

[0, 2, 12, 36]

## Explanation :  for loops are computationally expensive ,  instead we can used this arage to tackle the issue saving space and time

In [18]:
import numpy as np
def numpysum(n):
  a = np.arange(n) ** 2  #Creates an array [0,1,..n-1] and element-wise sqauring
  b = np.arange(n) ** 3
  c = a + b #element wise adding - NO LOOP Overhead, hence Memory Efficient
  return c

numpysum(4)

array([ 0,  2, 12, 36])

## Note : 
- Creating Arrays from Sequences
- a list of numbers will create a 1D array,
- a list of lists will create a 2D array,
- further nested lists will create higher-dimensional arrays. 
- In general, any array object is called an ndarray in NumPy

In [19]:
import numpy as np
np.array([127, 128, 129], dtype=np.int32) 

array([127, 128, 129], dtype=int32)

In [20]:
import numpy as np
np.array([127, 128, 129], dtype=np.int8) 

OverflowError: Python integer 128 out of bounds for int8

## Error explanation: since 128 cant be stored in 8 bit , it raises overflow error

In [22]:
#ARRAY CREATION FUNCTIONS
import numpy as np
print(np.arange(10) , "0 TO BEFORE 10, Step Value 1")
print(np.arange(2, 10, dtype=float)) # 2 to 10-1 range with 1 as step values by default , type as float
print(np.arange(2, 3, 0.1)) # 2 to 3-0.1 range with .1 as step values , type as float

[0 1 2 3 4 5 6 7 8 9] 0 TO BEFORE 10, Step Value 1
[2. 3. 4. 5. 6. 7. 8. 9.]
[2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]


## Diag function

In [ ]:
# numpy.diag can define either a square 2D array with given values along the diagonal or if given a 2D array 
# returns a 1D array that is only the diagonal elements. 
# The two array creation functions can be helpful while doing linear algebra, as such:

In [23]:
import numpy as np
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [25]:
np.diag([1, 2, 3], 1) # here 1 column shift is done

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [27]:
a = np.array([[1, 2], [3, 4]]) # it returns the diagonal elements
np.diag(a)

array([1, 4])

In [28]:
# np.diag(v, k=1):

# When v is a 1D array, np.diag creates a 2D square matrix with v placed along the k-th diagonal.

# k=1 → the diagonal above the main (first superdiagonal).

# To hold this upper diagonal, NumPy creates a (n + k) × (n + k) square matrix, where n is the length of the input array.

# So for [1, 2, 3]: Length = 3, k = 1, Matrix shape = 4 × 4

# # Diagonal values are placed at positions: (0,1), (1,2), (2,3)


## Vandermonde Matrix

In [29]:
import numpy as np
np.vander(np.linspace(0, 2, 5), 2) # linspace will split the range from 0 to 2 into 5 equal sets , and 2 is the n value

array([[0. , 1. ],
       [0.5, 1. ],
       [1. , 1. ],
       [1.5, 1. ],
       [2. , 1. ]])

## Explanation:
- the element to the power (N-1) .. next element to the power (N-2).. so on till n-x !=0;
- in the previous eg , 2 represents number of columns

In [30]:
np.vander([1, 2, 3, 4], 2) 

array([[1, 1],
       [2, 1],
       [3, 1],
       [4, 1]])

In [31]:
np.vander((1, 2, 3, 4), 4)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

In [32]:
#np.vander(x, N) creates a Vandermonde matrix from a 1D input array x.

# [[x₁**(N-1), x₁**(N-2), ..., x₁**0],
#  [x₂**(N-1), x₂**(N-2), ..., x₂**0],
#  ...
#  [xₙ**(N-1), xₙ**(N-2), ..., xₙ**0]]

# So each row is a decreasing power of an element from x.

## Indexing and Slicing
## 1. Slicing a NumPy Array

In [33]:
import numpy as np

# 1D Array
arr1 = np.array([10, 20, 30, 40, 50])
print("Original Array:", arr1)
print("Slice 1 to 4:", arr1[1:4])   # elements from index 1 to 3
print("Step of 2:", arr1[::2])      # every 2nd element

# 2D Array
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n2D Array:\n", arr2)
print("First row:", arr2[0, :])     # First row
print("Second column:", arr2[:, 1]) # Second column
print("Sub-matrix:\n", arr2[0:2, 1:3])  # Top-left 2x2 slice


Original Array: [10 20 30 40 50]
Slice 1 to 4: [20 30 40]
Step of 2: [10 30 50]

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
First row: [1 2 3]
Second column: [2 5 8]
Sub-matrix:
 [[2 3]
 [5 6]]


## 2. Slicing a Python List

In [34]:
# Normal Python list
my_list = [10, 20, 30, 40, 50]

# Slicing
print("Original List:", my_list)
print("Slice 1 to 4:", my_list[1:4])  # elements from index 1 to 3
print("Step of 2:", my_list[::2])     # every 2nd element


Original List: [10, 20, 30, 40, 50]
Slice 1 to 4: [20, 30, 40]
Step of 2: [10, 30, 50]


## 3. Mutability Test (Important Difference)
### NumPy slicing gives a view, not a copy → modifying the slice affects the original array.

In [35]:
# Python List - Immutable slice (copy)
list1 = [1, 2, 3, 4, 5]
list_slice = list1[1:4]
list_slice[0] = 99
print("Original List after slice change:", list1)   # unchanged

# NumPy Array - Mutable slice (view)
arr = np.array([1, 2, 3, 4, 5])
arr_slice = arr[1:4]
arr_slice[0] = 99
print("Original Array after slice change:", arr)    # changed


Original List after slice change: [1, 2, 3, 4, 5]
Original Array after slice change: [ 1 99  3  4  5]
